NWS_OFFICES = {
    "ABQ": "Albuquerque, NM",
    "ABR": "Aberdeen, SD",
    "AFC": "Anchorage, AK",
    "AJK": "Juneau, AK",
    "AKQ": "Wakefield, VA",
    "ALY": "Albany, NY",
    "AMA": "Amarillo, TX",
    "APX": "Gaylord, MI",
    "ARX": "La Crosse, WI",
    "AWC": "Aviation Weather Center",
    "BGM": "Binghamton, NY",
    "BIS": "Bismarck, ND",
    "BOI": "Boise, ID",
    "BOU": "Boulder/Denver, CO",
    "BOX": "Boston/Norton, MA",
    "BRO": "Brownsville, TX",
    "BTV": "Burlington, VT",
    "BUF": "Buffalo, NY",
    "CAE": "Columbia, SC",
    "CAR": "Caribou, ME",
    "CHS": "Charleston, SC",
    "CLE": "Cleveland, OH",
    "CRP": "Corpus Christi, TX",
    "CTP": "State College, PA",
    "CYS": "Cheyenne, WY",
    "DDC": "Dodge City, KS",
    "DLH": "Duluth, MN",
    "DMX": "Des Moines, IA",
    "DTX": "Detroit/Pontiac, MI",
    "DVN": "Quad Cities, IA",
    "EAX": "Kansas City/Pleasant Hill, MO",
    "EKA": "Eureka, CA",
    "EPZ": "El Paso, TX",
    "EWX": "Austin/San Antonio, TX",
    "FFC": "Peachtree City, GA",
    "FGF": "Grand Forks, ND",
    "FGZ": "Flagstaff, AZ",
    "FSD": "Sioux Falls, SD",
    "FWD": "Fort Worth/Dallas, TX",
    "GID": "Hastings, NE",
    "GJT": "Grand Junction, CO",
    "GLD": "Goodland, KS",
    "GRB": "Green Bay, WI",
    "GRR": "Grand Rapids, MI",
    "GSP": "Greenville/Spartanburg, SC",
    "GUM": "Guam",
    "GYX": "Portland/Gray, ME",
    "HFO": "Honolulu, HI",
    "HGX": "Houston/Galveston, TX",
    "HNX": "Hanford, CA",
    "HUN": "Huntsville, AL",
    "ICT": "Wichita, KS",
    "ILM": "Wilmington, NC",
    "ILN": "Cincinnati/Wilmington, OH",
    "ILX": "Lincoln, IL",
    "IND": "Indianapolis, IN",
    "IWX": "Northern Indiana",
    "JAN": "Jackson, MS",
    "JAX": "Jacksonville, FL",
    "JKL": "Jackson, KY",
    "KEY": "Key West, FL",
    "LBB": "Lubbock, TX",
    "LBF": "North Platte, NE",
    "LCH": "Lake Charles, LA",
    "LIX": "New Orleans/Baton Rouge, LA",
    "LKN": "Elko, NV",
    "LMK": "Louisville, KY",
    "LOT": "Chicago, IL",
    "LOX": "Los Angeles/Oxnard, CA",
    "LSX": "St. Louis, MO",
    "LWX": "Baltimore/Washington, DC",
    "LZK": "Little Rock, AR",
    "MAF": "Midland/Odessa, TX",
    "MEG": "Memphis, TN",
    "MFL": "Miami, FL",
    "MFR": "Medford, OR",
    "MHX": "Newport/Morehead City, NC",
    "MKX": "Milwaukee/Sullivan, WI",
    "MLB": "Melbourne, FL",
    "MOB": "Mobile, AL",
    "MPX": "Minneapolis/Chanhassen, MN",
    "MQT": "Marquette, MI",
    "MRX": "Knoxville/Tri-Cities, TN",
    "MSO": "Missoula, MT",
    "MTR": "San Francisco Bay Area, CA",
    "NHC": "National Hurricane Center",
    "OAX": "Omaha/Valley, NE",
    "OHX": "Nashville, TN",
    "OKX": "New York/Upton, NY",
    "OPC": "Ocean Prediction Center",
    "OTX": "Spokane, WA",
    "OUN": "Norman, OK",
    "PAH": "Paducah, KY",
    "PBZ": "Pittsburgh, PA",
    "PDT": "Pendleton, OR",
    "PHI": "Philadelphia/Mt Holly, NJ",
    "PIH": "Pocatello/Idaho Falls, ID",
    "PPG": "Pago Pago, AS",
    "PQR": "Portland, OR",
    "PSR": "Phoenix, AZ",
    "PUB": "Pueblo, CO",
    "RAH": "Raleigh, NC",
    "REV": "Reno, NV",
    "RIW": "Riverton, WY",
    "RLX": "Charleston, WV",
    "RNK": "Blacksburg/Roanoke, VA",
    "SEW": "Seattle, WA",
    "SGF": "Springfield, MO",
    "SHV": "Shreveport, LA",
    "SJU": "San Juan, PR",
    "SLC": "Salt Lake City, UT",
    "SPC": "Storm Prediction Center",
    "STO": "Sacramento, CA",
    "TAE": "Tallahassee, FL",
    "TAFB": "Tropical Analysis and Forecast Branch",
    "TBW": "Tampa Bay/Ruskin, FL",
    "TFX": "Great Falls, MT",
    "TOP": "Topeka, KS",
    "TSA": "Tulsa, OK",
    "TWC": "Tucson, AZ",
    "UNR": "Rapid City, SD",
    "VEF": "Las Vegas, NV",
    "WPC": "Weather Prediction Center",
    "CPC": "Climate Prediction Center",
}
